/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as StatsRouteImport } from './app/stats'
import { Route as SponsorsRouteImport } from './app/sponsors'
import { Route as SearchRouteImport } from './app/search'
import { Route as OpengraphRouteImport } from './app/opengraph'
import { Route as LoginRouteImport } from './app/login'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as CompanyRouteImport } from './app/$company'
import { Route as IndexRouteImport } from './app/index'
import { Route as ContributeIndexRouteImport } from './app/contribute/index'
import { Route as OgSearchRouteImport } from './app/og.search'
import { Route as OgCompanyRouteImport } from './app/og/$company'
import { Route as ContributeEditRouteImport } from './app/contribute/edit'
import { Route as ContributeAddRouteImport } from './app/contribute/add'
import { Route as ContributeEditCompanyRouteImport } from './app/contribute/edit.$company'
import { Route as ApiGithubForkRouteImport } from './app/api/github/fork'
import { Route as ApiGithubCreatePrRouteImport } from './app/api/github/create-pr'
import { Route as ApiGithubCompaniesRouteImport } from './app/api/github/companies'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphRoute = OpengraphRouteImport.update({
  id: '/opengraph',
  path: '/opengraph',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/$company',
  path: '/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/contribute/',
  path: '/contribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSearchRoute = OgSearchRouteImport.update({
  id: '/og/search',
  path: '/og/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCompanyRoute = OgCompanyRouteImport.update({
  id: '/og/$company',
  path: '/og/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeEditRoute = ContributeEditRouteImport.update({
  id: '/contribute/edit',
  path: '/contribute/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeAddRoute = ContributeAddRouteImport.update({
  id: '/contribute/add',
  path: '/contribute/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeEditCompanyRoute = ContributeEditCompanyRouteImport.update({
  id: '/$company',
  path: '/$company',
  getParentRoute: () => ContributeEditRoute,
} as any)
const ApiGithubForkRoute = ApiGithubForkRouteImport.update({
  id: '/api/github/fork',
  path: '/api/github/fork',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCreatePrRoute = ApiGithubCreatePrRouteImport.update({
  id: '/api/github/create-pr',
  path: '/api/github/create-pr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubCompaniesRoute = ApiGithubCompaniesRouteImport.update({
  id: '/api/github/companies',
  path: '/api/github/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/opengraph': typeof OpengraphRoute
  '/search': typeof SearchRoute
  '/sponsors': typeof SponsorsRoute
  '/stats': typeof StatsRoute
  '/contribute/add': typeof ContributeAddRoute
  '/contribute/edit': typeof ContributeEditRouteWithChildren
  '/og/$company': typeof OgCompanyRoute
  '/og/search': typeof OgSearchRoute
  '/contribute': typeof ContributeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/companies': typeof ApiGithubCompaniesRoute
  '/api/github/create-pr': typeof ApiGithubCreatePrRoute
  '/api/github/fork': typeof ApiGithubForkRoute
  '/contribute/edit/$company': typeof ContributeEditCompanyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/opengraph': typeof OpengraphRoute
  '/search': typeof SearchRoute
  '/sponsors': typeof SponsorsRoute
  '/stats': typeof StatsRoute
  '/contribute/add': typeof ContributeAddRoute
  '/contribute/edit': typeof ContributeEditRouteWithChildren
  '/og/$company': typeof OgCompanyRoute
  '/og/search': typeof OgSearchRoute
  '/contribute': typeof ContributeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/companies': typeof ApiGithubCompaniesRoute
  '/api/github/create-pr': typeof ApiGithubCreatePrRoute
  '/api/github/fork': typeof ApiGithubForkRoute
  '/contribute/edit/$company': typeof ContributeEditCompanyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$company': typeof CompanyRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/opengraph': typeof OpengraphRoute
  '/search': typeof SearchRoute
  '/sponsors': typeof SponsorsRoute
  '/stats': typeof StatsRoute
  '/contribute/add': typeof ContributeAddRoute
  '/contribute/edit': typeof ContributeEditRouteWithChildren
  '/og/$company': typeof OgCompanyRoute
  '/og/search': typeof OgSearchRoute
  '/contribute/': typeof ContributeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github/companies': typeof ApiGithubCompaniesRoute
  '/api/github/create-pr': typeof ApiGithubCreatePrRoute
  '/api/github/fork': typeof ApiGithubForkRoute
  '/contribute/edit/$company': typeof ContributeEditCompanyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$company'
    | '/dashboard'
    | '/login'
    | '/opengraph'
    | '/search'
    | '/sponsors'
    | '/stats'
    | '/contribute/add'
    | '/contribute/edit'
    | '/og/$company'
    | '/og/search'
    | '/contribute'
    | '/api/auth/$'
    | '/api/github/companies'
    | '/api/github/create-pr'
    | '/api/github/fork'
    | '/contribute/edit/$company'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$company'
    | '/dashboard'
    | '/login'
    | '/opengraph'
    | '/search'
    | '/sponsors'
    | '/stats'
    | '/contribute/add'
    | '/contribute/edit'
    | '/og/$company'
    | '/og/search'
    | '/contribute'
    | '/api/auth/$'
    | '/api/github/companies'
    | '/api/github/create-pr'
    | '/api/github/fork'
    | '/contribute/edit/$company'
  id:
    | '__root__'
    | '/'
    | '/$company'
    | '/dashboard'
    | '/login'
    | '/opengraph'
    | '/search'
    | '/sponsors'
    | '/stats'
    | '/contribute/add'
    | '/contribute/edit'
    | '/og/$company'
    | '/og/search'
    | '/contribute/'
    | '/api/auth/$'
    | '/api/github/companies'
    | '/api/github/create-pr'
    | '/api/github/fork'
    | '/contribute/edit/$company'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OpengraphRoute: typeof OpengraphRoute
  SearchRoute: typeof SearchRoute
  SponsorsRoute: typeof SponsorsRoute
  StatsRoute: typeof StatsRoute
  ContributeAddRoute: typeof ContributeAddRoute
  ContributeEditRoute: typeof ContributeEditRouteWithChildren
  OgCompanyRoute: typeof OgCompanyRoute
  OgSearchRoute: typeof OgSearchRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubCompaniesRoute: typeof ApiGithubCompaniesRoute
  ApiGithubCreatePrRoute: typeof ApiGithubCreatePrRoute
  ApiGithubForkRoute: typeof ApiGithubForkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph': {
      id: '/opengraph'
      path: '/opengraph'
      fullPath: '/opengraph'
      preLoaderRoute: typeof OpengraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$company': {
      id: '/$company'
      path: '/$company'
      fullPath: '/$company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/search': {
      id: '/og/search'
      path: '/og/search'
      fullPath: '/og/search'
      preLoaderRoute: typeof OgSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$company': {
      id: '/og/$company'
      path: '/og/$company'
      fullPath: '/og/$company'
      preLoaderRoute: typeof OgCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/edit': {
      id: '/contribute/edit'
      path: '/contribute/edit'
      fullPath: '/contribute/edit'
      preLoaderRoute: typeof ContributeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/add': {
      id: '/contribute/add'
      path: '/contribute/add'
      fullPath: '/contribute/add'
      preLoaderRoute: typeof ContributeAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/edit/$company': {
      id: '/contribute/edit/$company'
      path: '/$company'
      fullPath: '/contribute/edit/$company'
      preLoaderRoute: typeof ContributeEditCompanyRouteImport
      parentRoute: typeof ContributeEditRoute
    }
    '/api/github/fork': {
      id: '/api/github/fork'
      path: '/api/github/fork'
      fullPath: '/api/github/fork'
      preLoaderRoute: typeof ApiGithubForkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/create-pr': {
      id: '/api/github/create-pr'
      path: '/api/github/create-pr'
      fullPath: '/api/github/create-pr'
      preLoaderRoute: typeof ApiGithubCreatePrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/companies': {
      id: '/api/github/companies'
      path: '/api/github/companies'
      fullPath: '/api/github/companies'
      preLoaderRoute: typeof ApiGithubCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ContributeEditRouteChildren {
  ContributeEditCompanyRoute: typeof ContributeEditCompanyRoute
}

const ContributeEditRouteChildren: ContributeEditRouteChildren = {
  ContributeEditCompanyRoute: ContributeEditCompanyRoute,
}

const ContributeEditRouteWithChildren = ContributeEditRoute._addFileChildren(
  ContributeEditRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OpengraphRoute: OpengraphRoute,
  SearchRoute: SearchRoute,
  SponsorsRoute: SponsorsRoute,
  StatsRoute: StatsRoute,
  ContributeAddRoute: ContributeAddRoute,
  ContributeEditRoute: ContributeEditRouteWithChildren,
  OgCompanyRoute: OgCompanyRoute,
  OgSearchRoute: OgSearchRoute,
  ContributeIndexRoute: ContributeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubCompaniesRoute: ApiGithubCompaniesRoute,
  ApiGithubCreatePrRoute: ApiGithubCreatePrRoute,
  ApiGithubForkRoute: ApiGithubForkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
